In [1]:
%load_ext autoreload
%autoreload 2

In [95]:
from ccd import CCD, cartesian_product

In [102]:
ccd = CCD(Z=2)
t = ccd.t
print(t.shape)
print(t.sum())
print(t)

(6, 6, 6, 6)
-0.2640173004936749
[[[[ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]]

  [[ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.          0.          0.          0.          0.
     0.        ]]

  [[ 0.          0.          0.          0.          0.
     0.        ]
   [ 0.       

In [177]:
ccd = CCD(Z=2)
ccd.iterate()
print()
ccd.explicit_iterate()

0 : -2.752283772828832
1 : -2.7527826730437
2 : -2.7525968721919223
3 : -2.7526662078748436
4 : -2.7526403261474637
5 : -2.7526499936046687
6 : -2.7526463814238777
7 : -2.752647731497356
8 : -2.7526472267963564
9 : -2.7526474155009284

0 : -2.752283772828832
1 : -2.7527826730437
2 : -2.7525968721919223
3 : -2.7526662078748436
4 : -2.7526403261474637
5 : -2.7526499936046687
6 : -2.7526463814238777
7 : -2.752647731497356
8 : -2.7526472267963564
9 : -2.7526474155009284


In [4]:
f = ccd.h
v = ccd.v
print(ccd.energy())
t = ccd.initial_guess()
print(f.shape, v.shape, t.shape)
print(t.sum())

-0.001810714138913295
(6, 6) (6, 6, 6, 6) (6, 6, 6, 6)
-0.2640173004936749


In [12]:
a = ccd.initial_guess()
a[:, :, :, slice(2,5)].shape

(6, 6, 6, 3)

In [51]:
import numpy as np
a = np.arange(5*5).reshape((5,5))
print(a)
b = 2*np.ones((5,5))
c = np.zeros((5,5))
l = [1,3,4]
c[l,2:4] = a[l,2:4]/b[l,2:4]
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0.   0.   0.   0.   0. ]
 [ 0.   0.   3.5  4.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   8.5  9.   0. ]
 [ 0.   0.  11.  11.5  0. ]]


In [56]:
print(list(ccd.double_excitations()))
list(zip(*ccd.double_excitations()))

[(0, 0, 2, 2), (0, 0, 2, 4), (0, 1, 2, 3), (0, 1, 2, 5), (0, 0, 4, 2), (0, 0, 4, 4), (0, 1, 4, 3), (0, 1, 4, 5), (1, 0, 3, 2), (1, 0, 3, 4), (1, 1, 3, 3), (1, 1, 3, 5), (1, 0, 5, 2), (1, 0, 5, 4), (1, 1, 5, 3), (1, 1, 5, 5)]


[(0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1),
 (0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1),
 (2, 2, 2, 2, 4, 4, 4, 4, 3, 3, 3, 3, 5, 5, 5, 5),
 (2, 4, 3, 5, 2, 4, 3, 5, 2, 4, 3, 5, 2, 4, 3, 5)]

In [80]:
a = np.arange(10)
b = np.copy(a)
b[5] = 0
print(a, b)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 0 6 7 8 9]


In [97]:
from itertools import product
n = ccd.n
for k, l, m, n in cartesian_product(n, n, n, n):
    print(f"{k}, {l}, {m}, {n} = ", ccd.v[k, l, m, n], " ? ", (k, l, m, n) in ccd.double_excitations())

0, 0, 0, 0 =  0.0  ?  False
0, 0, 0, 1 =  0.0  ?  False
0, 0, 0, 2 =  0.0  ?  False
0, 0, 0, 3 =  0.0  ?  False
0, 0, 0, 4 =  0.0  ?  False
0, 0, 0, 5 =  0.0  ?  False
0, 0, 1, 0 =  0.0  ?  False
0, 0, 1, 1 =  0.0  ?  False
0, 0, 1, 2 =  0.0  ?  False
0, 0, 1, 3 =  0.0  ?  False
0, 0, 1, 4 =  0.0  ?  False
0, 0, 1, 5 =  0.0  ?  False
0, 0, 2, 0 =  0.0  ?  False
0, 0, 2, 1 =  0.0  ?  False
0, 0, 2, 2 =  0.0  ?  True
0, 0, 2, 3 =  0.0  ?  False
0, 0, 2, 4 =  0.0  ?  True
0, 0, 2, 5 =  0.0  ?  False
0, 0, 3, 0 =  0.0  ?  False
0, 0, 3, 1 =  0.0  ?  False
0, 0, 3, 2 =  0.0  ?  False
0, 0, 3, 3 =  0.0  ?  False
0, 0, 3, 4 =  0.0  ?  False
0, 0, 3, 5 =  0.0  ?  False
0, 0, 4, 0 =  0.0  ?  False
0, 0, 4, 1 =  0.0  ?  False
0, 0, 4, 2 =  0.0  ?  True
0, 0, 4, 3 =  0.0  ?  False
0, 0, 4, 4 =  0.0  ?  True
0, 0, 4, 5 =  0.0  ?  False
0, 0, 5, 0 =  0.0  ?  False
0, 0, 5, 1 =  0.0  ?  False
0, 0, 5, 2 =  0.0  ?  False
0, 0, 5, 3 =  0.0  ?  False
0, 0, 5, 4 =  0.0  ?  False
0, 0, 5, 5 =  0.0  ?  Fa

1, 4, 3, 3 =  0.0  ?  False
1, 4, 3, 4 =  0.004857706356854169  ?  False
1, 4, 3, 5 =  0.0  ?  False
1, 4, 4, 0 =  0.0  ?  False
1, 4, 4, 1 =  -0.198974609375  ?  False
1, 4, 4, 2 =  0.0  ?  False
1, 4, 4, 3 =  -0.004857706356854169  ?  False
1, 4, 4, 4 =  0.0  ?  False
1, 4, 4, 5 =  -0.0022622638577071527  ?  False
1, 4, 5, 0 =  0.01153564453125  ?  False
1, 4, 5, 1 =  0.0  ?  False
1, 4, 5, 2 =  0.004218077669259728  ?  False
1, 4, 5, 3 =  0.0  ?  False
1, 4, 5, 4 =  0.0022622638577071527  ?  False
1, 4, 5, 5 =  0.0  ?  False
1, 5, 0, 0 =  0.0  ?  False
1, 5, 0, 1 =  0.0  ?  False
1, 5, 0, 2 =  0.0  ?  False
1, 5, 0, 3 =  0.0  ?  False
1, 5, 0, 4 =  0.0  ?  False
1, 5, 0, 5 =  0.0  ?  False
1, 5, 1, 0 =  0.0  ?  False
1, 5, 1, 1 =  0.0  ?  False
1, 5, 1, 2 =  0.0  ?  False
1, 5, 1, 3 =  0.07860711682899044  ?  False
1, 5, 1, 4 =  0.0  ?  False
1, 5, 1, 5 =  0.18743896484375  ?  False
1, 5, 2, 0 =  0.0  ?  False
1, 5, 2, 1 =  0.0  ?  False
1, 5, 2, 2 =  0.0  ?  False
1, 5, 2, 3 =  0.0

4, 2, 2, 3 =  0.0  ?  False
4, 2, 2, 4 =  -0.15327580159999998  ?  False
4, 2, 2, 5 =  0.0  ?  False
4, 2, 3, 0 =  0.0  ?  False
4, 2, 3, 1 =  0.0  ?  False
4, 2, 3, 2 =  0.0  ?  False
4, 2, 3, 3 =  0.0  ?  False
4, 2, 3, 4 =  0.0  ?  False
4, 2, 3, 5 =  0.0  ?  False
4, 2, 4, 0 =  0.0006396286875944412  ?  False
4, 2, 4, 1 =  0.0  ?  False
4, 2, 4, 2 =  0.15327580159999998  ?  False
4, 2, 4, 3 =  0.0  ?  False
4, 2, 4, 4 =  0.0  ?  False
4, 2, 4, 5 =  0.0  ?  False
4, 2, 5, 0 =  0.0  ?  False
4, 2, 5, 1 =  0.0  ?  False
4, 2, 5, 2 =  0.0  ?  False
4, 2, 5, 3 =  0.0  ?  False
4, 2, 5, 4 =  0.0  ?  False
4, 2, 5, 5 =  0.0  ?  False
4, 3, 0, 0 =  0.0  ?  False
4, 3, 0, 1 =  0.022445836996582154  ?  False
4, 3, 0, 2 =  0.0  ?  False
4, 3, 0, 3 =  0.00787190185136582  ?  False
4, 3, 0, 4 =  0.0  ?  False
4, 3, 0, 5 =  0.004218077669259728  ?  False
4, 3, 1, 0 =  -0.022445836996582154  ?  False
4, 3, 1, 1 =  0.0  ?  False
4, 3, 1, 2 =  -0.009085693750900134  ?  False
4, 3, 1, 3 =  0.0  ?  F

5, 3, 2, 1 =  0.0  ?  False
5, 3, 2, 2 =  0.0  ?  False
5, 3, 2, 3 =  0.0  ?  False
5, 3, 2, 4 =  0.0  ?  False
5, 3, 2, 5 =  0.0  ?  False
5, 3, 3, 0 =  0.0  ?  False
5, 3, 3, 1 =  0.0012137918995343139  ?  False
5, 3, 3, 2 =  0.0  ?  False
5, 3, 3, 3 =  0.0  ?  False
5, 3, 3, 4 =  0.0  ?  False
5, 3, 3, 5 =  -0.15327580159999998  ?  False
5, 3, 4, 0 =  0.0  ?  False
5, 3, 4, 1 =  0.0  ?  False
5, 3, 4, 2 =  0.0  ?  False
5, 3, 4, 3 =  0.0  ?  False
5, 3, 4, 4 =  0.0  ?  False
5, 3, 4, 5 =  0.0  ?  False
5, 3, 5, 0 =  0.0  ?  False
5, 3, 5, 1 =  0.0006396286875944412  ?  False
5, 3, 5, 2 =  0.0  ?  False
5, 3, 5, 3 =  0.15327580159999998  ?  False
5, 3, 5, 4 =  0.0  ?  False
5, 3, 5, 5 =  0.0  ?  False
5, 4, 0, 0 =  0.0  ?  False
5, 4, 0, 1 =  -0.01153564453125  ?  False
5, 4, 0, 2 =  0.0  ?  False
5, 4, 0, 3 =  -0.004218077669259728  ?  False
5, 4, 0, 4 =  0.0  ?  False
5, 4, 0, 5 =  -0.0022622638577071527  ?  False
5, 4, 1, 0 =  0.01153564453125  ?  False
5, 4, 1, 1 =  0.0  ?  False

In [131]:
from ccd import CCD
ccd = CCD(Z=2)
print(ccd.num_holes, ccd.num_particles)
print(ccd.hole_ind, ccd.particle_ind)
print(ccd.virtual, ccd.core)
print(list(ccd.hhpp()))

2 2 0 0 -1.0
2 3 0 0 -1.0
2 4 0 0 -0.7222222222222222
2 5 0 0 -0.7222222222222222
3 2 0 0 -1.0
3 3 0 0 -1.0
3 4 0 0 -0.7222222222222222
3 5 0 0 -0.7222222222222222
4 2 0 0 -0.7222222222222222
4 3 0 0 -0.7222222222222222
4 4 0 0 -0.4444444444444444
4 5 0 0 -0.4444444444444444
5 2 0 0 -0.7222222222222222
5 3 0 0 -0.7222222222222222
5 4 0 0 -0.4444444444444444
5 5 0 0 -0.4444444444444444
2 2 0 1 -1.0
2 3 0 1 -1.0
2 4 0 1 -0.7222222222222222
2 5 0 1 -0.7222222222222222
3 2 0 1 -1.0
3 3 0 1 -1.0
3 4 0 1 -0.7222222222222222
3 5 0 1 -0.7222222222222222
4 2 0 1 -0.7222222222222222
4 3 0 1 -0.7222222222222222
4 4 0 1 -0.4444444444444444
4 5 0 1 -0.4444444444444444
5 2 0 1 -0.7222222222222222
5 3 0 1 -0.7222222222222222
5 4 0 1 -0.4444444444444444
5 5 0 1 -0.4444444444444444
2 2 1 0 -1.0
2 3 1 0 -1.0
2 4 1 0 -0.7222222222222222
2 5 1 0 -0.7222222222222222
3 2 1 0 -1.0
3 3 1 0 -1.0
3 4 1 0 -0.7222222222222222
3 5 1 0 -0.7222222222222222
4 2 1 0 -0.7222222222222222
4 3 1 0 -0.7222222222222222
4 4 